/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_kpu_opencvtest6_MainActivity */

#ifndef _Included_kr_ac_kpu_opencvtest6_MainActivity
#define _Included_kr_ac_kpu_opencvtest6_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef kr_ac_kpu_opencvtest6_MainActivity_CAMERA_PERMISSION_REQUEST_CODE
#define kr_ac_kpu_opencvtest6_MainActivity_CAMERA_PERMISSION_REQUEST_CODE 200L
/*
 * Class:     kr_ac_kpu_opencvtest6_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_kr_ac_kpu_opencvtest6_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
